CREATE DATABASE CSE_3B_421

CREATE TABLE BRANCH(
BNAME VARCHAR(50),
CITY VARCHAR(50)
)
INSERT INTO BRANCH VALUES
('VRCE', 'NAGPUR'),
('AJNI' ,'NAGPUR'),
('KAROLBAGH','DELHI'),
('HANDI','DELHI'),
('DHARAMPETH','NAGPUR'),
('M.G. ROAD' ,'BANGLORE'),
('ANDHERI' ,'BOMBAY'),
('VIRAR','BOMBAY'),
('NEHRU PLACE', 'DELHI'),
('POWAI' ,'BOMBAY')

SELECT * FROM BRANCH